name: Check and publish addon

on: [push]

env:
  ADDON_NAME: script.service.hyperion
  TARGET_KODI_VER: nexus

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install addon checker
      run: |
        pip install -q kodi-addon-checker
    - name: Check with addon-checker
      run: |
        kodi-addon-checker --branch $TARGET_KODI_VER --allow-folder-id-mismatch $ADDON_NAME

  release:
    runs-on: ubuntu-latest

    needs: check
    if: github.ref_type == 'tag'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install addon submitter
      run: |
        pip install -q git+https://github.com/xbmc/kodi-addon-submitter.git
    - name: Submit addon
      run: |
        submit-addon -s -z $ADDON_NAME
        ls -la *.zip
    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${ADDON_NAME}-*.zip"
